# Generated by Django 4.2.6 on 2023-10-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspiece',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
